/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gradecalculatorv3;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ethan_2
 */
public class EditingClassesForm extends javax.swing.JPanel {

    /**
     * Creates new form EditingClassesForm
     */
    public EditingClassesForm(JFrame frame) {
        initComponents();

        // Create the JFrame for this window.
        frame.add(this);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        // Below is custom close operation.
        WindowListener exitListener = new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                // Show the GPA calculator form on closing this form.
                GPACalculator gpacalc = new GPACalculator();
                String[] arguments = {};
                gpacalc.main(arguments);

            }
        };
        frame.addWindowListener(exitListener);  // Add the custom designed listener.

        classNameTextField.setEditable(false);
        finalGradeTextField.setEditable(false);
        semesterTextField.setEditable(false);
        creditsTextField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        classesComboBox = new javax.swing.JComboBox<>();
        classNameTextField = new javax.swing.JTextField();
        creditsTextField = new javax.swing.JTextField();
        finalGradeTextField = new javax.swing.JTextField();
        semesterTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addAClassButton = new javax.swing.JButton();

        classesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Class name:");

        jLabel2.setText("Final grade:");

        jLabel3.setText("Semester:");

        jLabel4.setText("Credits:");

        addAClassButton.setText("Add a Class");
        addAClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAClassButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(classesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(semesterTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(classNameTextField)
                            .addComponent(creditsTextField)
                            .addComponent(finalGradeTextField))
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addAClassButton)
                        .addGap(134, 134, 134))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(classesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(creditsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(finalGradeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(semesterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(41, 41, 41)
                .addComponent(addAClassButton)
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addAClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAClassButtonActionPerformed
        if (addAClassButton.getText().equals("Add a Class")) {
            classesComboBox.setVisible(false);
            addAClassButton.setText("Submit");
            classNameTextField.setText("");
            finalGradeTextField.setText("");
            semesterTextField.setText("");
            creditsTextField.setText("");

            classNameTextField.requestFocusInWindow();
            addAClassButton.setText("Submit");
            classNameTextField.setEditable(true);
            finalGradeTextField.setEditable(true);
            semesterTextField.setEditable(true);
            creditsTextField.setEditable(true);

        } else {
            // Try submitting to database.
            try {
                Querying q = new Querying();
                q.submitNewClass(classNameTextField.getText(), finalGradeTextField.getText(), creditsTextField.getText(), semesterTextField.getText());
                JOptionPane.showMessageDialog(this,
                        "Successfully added the class.",
                        "Class Added",
                        JOptionPane.INFORMATION_MESSAGE);
                classesComboBox.addItem(classNameTextField.getText());
                classesComboBox.setSelectedIndex(classesComboBox.getItemCount() - 1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);  // Show the exception message.
            }

            classesComboBox.setVisible(true);
            addAClassButton.setText("Add a Class");
            classNameTextField.setEditable(false);
            finalGradeTextField.setEditable(false);
            semesterTextField.setEditable(false);
            creditsTextField.setEditable(false);

        }
    }//GEN-LAST:event_addAClassButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAClassButton;
    private javax.swing.JTextField classNameTextField;
    private javax.swing.JComboBox<String> classesComboBox;
    private javax.swing.JTextField creditsTextField;
    private javax.swing.JTextField finalGradeTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField semesterTextField;
    // End of variables declaration//GEN-END:variables
}
