/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gradecalculatorv3;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ethan_2
 */
public class FinalGradesForm extends javax.swing.JPanel {

    /**
     * Creates new form EditingClassesForm
     */
    public FinalGradesForm(JFrame frame) {
        initComponents();
        super.setOpaque(true);
        this.setBackground(Color.cyan);

        // Create the JFrame for this window.
        frame.add(this);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        // Below is custom close operation.
        WindowListener exitListener = new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                // Show the GPA calculator form on closing this form.
                GPACalculator gpacalc = new GPACalculator();
                String[] arguments = {};
                gpacalc.main(arguments);

            }
        };
        frame.addWindowListener(exitListener);  // Add the custom designed listener.

        classNameTextField.setEditable(false);
        finalGradeTextField.setEditable(false);
        semesterTextField.setEditable(false);
        creditsTextField.setEditable(false);

        // make pressing the Enter key the same as clicking the mouse
        frame.getRootPane().setDefaultButton(addAClassButton);

        try {
            // fetch courses, place them in the combo box
            LinkedList<String> courses = new Querying().getCourses();
            classesComboBox.removeAllItems();
            for (int i = 0; i < courses.size(); i++) {
                classesComboBox.addItem(courses.get(i));
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex);  // Show the exception message.
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        classesComboBox = new javax.swing.JComboBox<>();
        classNameTextField = new javax.swing.JTextField();
        creditsTextField = new javax.swing.JTextField();
        finalGradeTextField = new javax.swing.JTextField();
        semesterTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addAClassButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setForeground(new java.awt.Color(102, 255, 255));
        setOpaque(false);

        classesComboBox.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        classesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        classesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classesComboBoxActionPerformed(evt);
            }
        });

        classNameTextField.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        classNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                classNameTextFieldFocusGained(evt);
            }
        });
        classNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                classNameTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                classNameTextFieldKeyReleased(evt);
            }
        });

        creditsTextField.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        creditsTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                creditsTextFieldFocusGained(evt);
            }
        });
        creditsTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                creditsTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                creditsTextFieldKeyReleased(evt);
            }
        });

        finalGradeTextField.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        finalGradeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                finalGradeTextFieldFocusGained(evt);
            }
        });
        finalGradeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                finalGradeTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                finalGradeTextFieldKeyReleased(evt);
            }
        });

        semesterTextField.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("Class name:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("Final grade:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("Semester:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Credits:");

        addAClassButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        addAClassButton.setText("Add a Class");
        addAClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAClassButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        deleteButton.setText("Delete Class");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addAClassButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(finalGradeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(semesterTextField)
                            .addComponent(creditsTextField)
                            .addComponent(classNameTextField))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(classesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(creditsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(finalGradeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(semesterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(41, 41, 41)
                .addComponent(addAClassButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addAClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAClassButtonActionPerformed
        if (addAClassButton.getText().equals("Add a Class")) {
            classesComboBox.setVisible(false);
            addAClassButton.setText("Submit");
            deleteButton.setText("Cancel");
            classNameTextField.setText("");
            finalGradeTextField.setText("");
            semesterTextField.setText("");
            creditsTextField.setText("");

            classNameTextField.requestFocusInWindow();
            addAClassButton.setText("Submit");
            classNameTextField.setEditable(true);
            finalGradeTextField.setEditable(true);
            semesterTextField.setEditable(true);
            creditsTextField.setEditable(true);

        } else {
            // Try submitting to database.
            try {
                Querying q = new Querying();
                q.submitNewClass(classNameTextField.getText().toUpperCase(), finalGradeTextField.getText().toUpperCase(), creditsTextField.getText(), semesterTextField.getText().toUpperCase());
                classesComboBox.addItem(classNameTextField.getText().toUpperCase());
                classesComboBox.setSelectedIndex(classesComboBox.getItemCount() - 1);
                JOptionPane.showMessageDialog(this,
                        "Successfully added the class.",
                        "Class Added",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);  // Show the exception message.
                classesComboBox.setSelectedIndex(0);
            }

            classesComboBox.setVisible(true);
            deleteButton.setText("Delete Class");
            addAClassButton.setText("Add a Class");
            classNameTextField.setEditable(false);
            finalGradeTextField.setEditable(false);
            semesterTextField.setEditable(false);
            creditsTextField.setEditable(false);

        }
    }//GEN-LAST:event_addAClassButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (deleteButton.getText().equals("Cancel")) {  //canceling out of adding a class

            classesComboBox.setVisible(true);
            deleteButton.setText("Delete Class");
            addAClassButton.setText("Add a Class");
            classNameTextField.setEditable(false);
            finalGradeTextField.setEditable(false);
            semesterTextField.setEditable(false);
            creditsTextField.setEditable(false);
            classesComboBox.setSelectedIndex(0);
        } else if (classesComboBox.getItemCount() > 0 && JOptionPane.showConfirmDialog(null, "Are you sure you would like to delete the course?", "Confirm",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            String className = classesComboBox.getSelectedItem().toString();

            try {
                // remove it from the database
                Querying q = new Querying();
                q.deleteClass(className);
                System.out.println(classesComboBox.getItemCount());
                classesComboBox.removeItemAt(classesComboBox.getSelectedIndex());
                JOptionPane.showMessageDialog(null, "Successfully deleted the class!");  // Show the exception message.
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, ex);  // Show the exception message.
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void classesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classesComboBoxActionPerformed
        if (classesComboBox.getItemCount() > 0) {
            try {
                String courseInfo[] = new Querying().getCourseInfo(classesComboBox.getSelectedItem().toString());
                classNameTextField.setText(courseInfo[0]);
                finalGradeTextField.setText(courseInfo[1]);
                semesterTextField.setText(courseInfo[2]);
                creditsTextField.setText(courseInfo[3]);
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, ex);  // Show the exception message.
            } catch (NullPointerException npe) {
                System.out.println("No other classes to display.");
            }
        }
    }//GEN-LAST:event_classesComboBoxActionPerformed

    private void classNameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_classNameTextFieldKeyPressed

    }//GEN-LAST:event_classNameTextFieldKeyPressed

    private void creditsTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_creditsTextFieldKeyPressed

    }//GEN-LAST:event_creditsTextFieldKeyPressed

    private void finalGradeTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_finalGradeTextFieldKeyPressed

    }//GEN-LAST:event_finalGradeTextFieldKeyPressed

    private void classNameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_classNameTextFieldKeyReleased
        // the entire name has been entered; move on to next textfield
        if (classNameTextField.getText().toString().length() == 6) {
            creditsTextField.requestFocusInWindow();
        }
    }//GEN-LAST:event_classNameTextFieldKeyReleased

    private void creditsTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_creditsTextFieldKeyReleased
        if (creditsTextField.getText().length() == 1) {
            finalGradeTextField.requestFocusInWindow();
        }
    }//GEN-LAST:event_creditsTextFieldKeyReleased

    private void finalGradeTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_finalGradeTextFieldKeyReleased
        // The grade has been entered. Move on.
        if (finalGradeTextField.getText().length() == 1) {
            semesterTextField.requestFocusInWindow();
        }
    }//GEN-LAST:event_finalGradeTextFieldKeyReleased

    private void classNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_classNameTextFieldFocusGained
        if (classNameTextField.getText().length() == 6) {
            classNameTextField.setText("");
        }
    }//GEN-LAST:event_classNameTextFieldFocusGained

    private void creditsTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creditsTextFieldFocusGained
        if (creditsTextField.getText().length() == 1) {
            creditsTextField.setText("");
        }
    }//GEN-LAST:event_creditsTextFieldFocusGained

    private void finalGradeTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_finalGradeTextFieldFocusGained
        if (finalGradeTextField.getText().length() == 1) {
            finalGradeTextField.setText("");
        }
    }//GEN-LAST:event_finalGradeTextFieldFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAClassButton;
    private javax.swing.JTextField classNameTextField;
    private javax.swing.JComboBox<String> classesComboBox;
    private javax.swing.JTextField creditsTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField finalGradeTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField semesterTextField;
    // End of variables declaration//GEN-END:variables
}
